name: Skew Lab
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
